/**
 * Config Server for Y-Router
 * 
 * Simple HTTP server that handles saving configuration to .env file
 * and restarting the y-router container.
 */

const http = require('http');
const fs = require('fs');
const path = require('path');
const { exec } = require('child_process');

const CONFIG_PORT = 8788;
const ENV_FILE = path.join(__dirname, '.env');

// CORS headers
const corsHeaders = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type',
    'Content-Type': 'application/json'
};

// Read current .env config
function readConfig() {
    const config = {};

    try {
        if (fs.existsSync(ENV_FILE)) {
            const content = fs.readFileSync(ENV_FILE, 'utf-8');
            content.split('\n').forEach(line => {
                const trimmed = line.trim();
                if (trimmed && !trimmed.startsWith('#')) {
                    const eqIndex = trimmed.indexOf('=');
                    if (eqIndex > 0) {
                        const key = trimmed.substring(0, eqIndex).trim();
                        let value = trimmed.substring(eqIndex + 1).trim();
                        // Remove quotes if present
                        if ((value.startsWith('"') && value.endsWith('"')) ||
                            (value.startsWith("'") && value.endsWith("'"))) {
                            value = value.slice(1, -1);
                        }
                        config[key] = value;
                    }
                }
            });
        }
    } catch (err) {
        console.error('Error reading .env:', err);
    }

    return config;
}

// Write config to .env file
function writeConfig(config) {
    try {
        const content = `# Y-Router Configuration
# Auto-generated by config-server

# OpenRouter Base URL
OPENROUTER_BASE_URL=${config.OPENROUTER_BASE_URL || 'https://openrouter.ai/api/v1'}

# Model Mapping Configuration
# Map Claude models to OpenRouter models
MODEL_MAP_OPUS=${config.MODEL_MAP_OPUS || ''}
MODEL_MAP_SONNET=${config.MODEL_MAP_SONNET || ''}
MODEL_MAP_HAIKU=${config.MODEL_MAP_HAIKU || ''}
`;

        fs.writeFileSync(ENV_FILE, content, 'utf-8');
        console.log('Config saved to .env');
        return true;
    } catch (err) {
        console.error('Error writing .env:', err);
        return false;
    }
}

// Restart y-router container (need down/up to reload .env)
function restartServer() {
    return new Promise((resolve) => {
        console.log('Restarting y-router container (down/up to reload .env)...');
        // Need to use down then up to reload .env file - restart doesn't reload env
        exec('docker compose down y-router && docker compose up y-router -d', { cwd: __dirname }, (error, stdout, stderr) => {
            if (error) {
                console.error('Restart error:', error);
                console.error('Stderr:', stderr);
                resolve(false);
            } else {
                console.log('Restart output:', stdout);
                resolve(true);
            }
        });
    });
}


const server = http.createServer(async (req, res) => {
    const url = new URL(req.url || '/', `http://localhost:${CONFIG_PORT}`);

    // Handle CORS preflight
    if (req.method === 'OPTIONS') {
        res.writeHead(200, corsHeaders);
        res.end();
        return;
    }

    // GET /config - Read current config
    if (url.pathname === '/config' && req.method === 'GET') {
        const fullConfig = readConfig();
        const config = {
            opus: fullConfig.MODEL_MAP_OPUS || '',
            sonnet: fullConfig.MODEL_MAP_SONNET || '',
            haiku: fullConfig.MODEL_MAP_HAIKU || ''
        };

        res.writeHead(200, corsHeaders);
        res.end(JSON.stringify(config));
        return;
    }

    // POST /config - Save config and restart
    if (url.pathname === '/config' && req.method === 'POST') {
        let body = '';

        req.on('data', chunk => {
            body += chunk.toString();
        });

        req.on('end', async () => {
            try {
                const { opus, sonnet, haiku } = JSON.parse(body);

                const currentConfig = readConfig();
                currentConfig.MODEL_MAP_OPUS = opus || '';
                currentConfig.MODEL_MAP_SONNET = sonnet || '';
                currentConfig.MODEL_MAP_HAIKU = haiku || '';

                const saved = writeConfig(currentConfig);

                if (saved) {
                    const restarted = await restartServer();
                    res.writeHead(200, corsHeaders);
                    res.end(JSON.stringify({
                        success: true,
                        restarted,
                        message: restarted ? 'Config saved and server restarting...' : 'Config saved but restart failed'
                    }));
                } else {
                    res.writeHead(500, corsHeaders);
                    res.end(JSON.stringify({ success: false, error: 'Failed to save config' }));
                }
            } catch (err) {
                res.writeHead(400, corsHeaders);
                res.end(JSON.stringify({ success: false, error: err.message }));
            }
        });
        return;
    }

    // Health check
    if (url.pathname === '/health' && req.method === 'GET') {
        res.writeHead(200, corsHeaders);
        res.end(JSON.stringify({ status: 'ok' }));
        return;
    }

    // 404 for everything else
    res.writeHead(404, corsHeaders);
    res.end(JSON.stringify({ error: 'Not Found' }));
});

server.listen(CONFIG_PORT, () => {
    console.log(`Config server running on http://localhost:${CONFIG_PORT}`);
    console.log('Endpoints:');
    console.log('  GET  /config - Get current model mapping config');
    console.log('  POST /config - Save config and restart server');
    console.log('  GET  /health - Health check');
});
